Disable typescript compiler for API schema in unit tests #7845
Because this bring no value at all, and is potentially CPU expensive when
running tests and might even lead to error TS2590, we disable it altogether.